name: check-pull-request

on: [pull_request]

jobs:
  run:
    runs-on: self-hosted
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - id: action-size
      name: Size
      uses: actions-ecosystem/action-size@v2

    - id: action-remove-labels
      name: Remove labels
      uses: actions-ecosystem/action-remove-labels@v1
      with:
          github_token: ${{ github.token }}
          labels: ${{ steps.action-size.outputs.stale_labels }}
    - id: hack
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          labels: |
            passed
            hack

